graph TD;

  subgraph Resume1["Software Engineer"]
    id1[ID: eb385761-8450-4b43-ad60-7c5d1b608e6e]
    subgraph Summary1
      id2[ID: ff835c82-0765-4d7f-a857-e157fd613ab7]
      goals1["Goals: To build scalable software solutions."]
      persona1["Persona: Innovative and problem-solving oriented."]
    end
    subgraph Skills1
      skill1["JavaScript"]
      skill2["React"]
      skill3["Node.js"]
    end
    subgraph Education1
      id3[ID: 29b014a1-cf90-4c39-8898-d5fe9e935bd8]
      summary1["B.Sc in Computer Science from ABC University"]
    end
    subgraph Schools1
      id4[ID: 4288ded1-4b5f-4bf4-ad93-9fbc942f2b5f]
      school1["ABC University"]
    end
    subgraph Degrees1
      degree1["Computer Science (2015-2019)"]
      degree2["Software Engineering (2014-2018)"]
    end
    subgraph Experience1
      id5[ID: 5fcb6df7-267f-48c4-9ed8-8450f8924f84]
      title1["Title: Lead Developer at XYZ Corp"]
      text1["Text: Led a team of developers in creating a new SaaS product."]
    end
    subgraph Companies1
      id6[ID: 88f5589a-c3dd-421e-9a3b-907fdb2fda27]
      company1["XYZ Corp"]
      role1["Role: Lead Developer"]
      duration1["(2019-2022)"]
    end
    subgraph Engagements1
      engagement1["Acme Inc. (2019)"]
      engagement2["Umbrella Co. (2021)"]
    end
    subgraph Accomplishments1
      accomplishment1["Increased code efficiency by 30%"]
      description1["Description: Implemented caching strategies to improve performance."]
      accomplishment2["Optimized data storage"]
      description2["Description: Redesigned database schema for better query performance."]
    end
    subgraph ContactInformation1
      id7[ID: acb8aa35-ea29-47d0-a8cc-d0b472684643]
      name1["Name: John Doe"]
      email1["Email: john.doe@example.com"]
      phone1["Phone: +1234567890"]
    end
    subgraph References1
      reference1["Jane Smith: +0987654321"]
      reference2["Sarah Connor: +1346798520"]
    end
  end

  subgraph Resume2["Tech Lead"]
    id8[ID: a2f4ffc6-e110-4b05-919f-8afb52a2ef75]
    subgraph Summary2
      id9[ID: 52460d50-4c6f-4d72-a725-c982789a753d]
      goals2["Goals: To lead innovative tech projects."]
      persona2["Persona: Dynamic and results-driven."]
    end
    subgraph Skills2
      skill4["Python"]
      skill5["AWS"]
      skill6["TypeScript"]
    end
    subgraph Education2
      id10[ID: 9c3e0016-4502-4c3a-b706-ea66c4a998e0]
      summary2["B.Tech in Information Technology from XYZ Institute"]
    end
    subgraph Schools2
      id11[ID: 70ac624d-4366-46ba-90a8-6af7545b89c5]
      school2["XYZ Institute"]
    end
    subgraph Degrees2
      degree3["Information Technology (2016-2020)"]
      degree4["Network Security (2017-2021)"]
    end
    subgraph Experience2
      id12[ID: fde144e7-db51-47d5-a0ed-ab08695d81a9]
      title2["Title: Software Engineer at Tech Innovations Ltd."]
      text2["Text: Developed innovative software solutions for clients."]
    end
    subgraph Companies2
      id13[ID: fcaa0f49-4fa9-4131-a292-b0cd80dfeb45]
      company2["Tech Innovations Ltd."]
      role2["Role: Software Engineer"]
      duration2["(2018-2020)"]
    end
    subgraph Engagements2
      engagement3["Globex Corp. (2020)"]
      engagement4["Cyberdyne Systems (2017-2018)"]
    end
    subgraph Accomplishments2
      accomplishment3["Led a successful migration to cloud infrastructure"]
      description3["Description: Managed project to migrate services to AWS."]
      accomplishment4["Improved application security"]
      description4["Description: Implemented a security audit and remediation plan."]
    end
    subgraph ContactInformation2
      id14[ID: 151821de-7dc9-48bc-b357-3f2fd5f44b85]
      name2["Name: Jane Doe"]
      email2["Email: jane.doe@example.com"]
      phone2["Phone: +0987654321"]
    end
    subgraph References2
      reference3["Tom Johnson: +1122334455"]
      reference4["Kyle Reese: +1230984567"]
    end
  end

  Resume1 -->|hasOne| Summary1
  Resume1 -->|hasMany| Skills1
  Resume1 -->|hasOne| Education1
  Resume1 -->|hasOne| Experience1
  Resume1 -->|hasOne| ContactInformation1
  Education1 -->|hasMany| Schools1
  Schools1 -->|hasMany| Degrees1
  Experience1 -->|hasMany| Companies1
  Companies1 -->|hasMany| Engagements1
  Engagements1 -->|hasMany| Accomplishments1
  ContactInformation1 -->|hasMany| References1

  Resume2 -->|hasOne| Summary2
  Resume2 -->|hasMany| Skills2
  Resume2 -->|hasOne| Education2
  Resume2 -->|hasOne| Experience2
  Resume2 -->|hasOne| ContactInformation2
  Education2 -->|hasMany| Schools2
  Schools2 -->|hasMany| Degrees2
  Experience2 -->|hasMany| Companies2
  Companies2 -->|hasMany| Engagements2
  Engagements2 -->|hasMany| Accomplishments2
  ContactInformation2 -->|hasMany| References2
