projects:
  resumebuilder:
    schemaPath: amplify/backend/api/resumebuilder/build/schema.graphql
    includes:
      - app/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: app/graphql
        region: us-east-2
        apiId: null
        maxDepth: 4
  pbradygeorgen:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
