version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 18
        - echo "Node version $(node -v)"
        - echo "NPM version $(npm -v)"
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  customHeaders:
    - pattern: '**/*.{js,css}'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=31536000, immutable'
    - pattern: '**/*.{jpg,jpeg,png,gif,ico,svg,webp}'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=31536000, immutable'
    - pattern: '**/*.{pdf}'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=86400'
    - pattern: '**/*.{html}'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=0, must-revalidate'
    - pattern: '/'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=0, must-revalidate'
  redirects:
    - source: '</^[^.]+$|\.(?!(html|js|css|json|svg|png|jpg|jpeg|gif|webp|ico|pdf)$)([^.]+$)/>'
      target: '/index.html'
      status: '200'
