#!/bin/bash
set -e

echo "🛠️ Chief O'Brien: Deploying LCARS Token Map..."

# Define target directory and file path
TOKEN_DIR="tokens"
TOKEN_FILE="$TOKEN_DIR/lcars-token-map.ts"

# Create the directory if it doesn't exist
mkdir -p "$TOKEN_DIR"

# Write the token map
cat <<EOF >"$TOKEN_FILE"
// 🧬 LCARS Design Tokens (auto-generated by O'Brien & Data)

export const colors = {
  alertRed: '#ff3b30',
  statusYellow: '#ffcc00',
  successGreen: '#4cd964',
  lcarsBlue: '#0096ff',
  lcarsOrange: '#ff9900',
  lcarsTan: '#ffcc99',
  lcarsBlack: '#1c1c1c',
  lcarsGray: '#888888',
};

export const spacing = {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '40px',
};

export const fonts = {
  heading: '"Eurostile", "Orbitron", sans-serif',
  body: '"LCARS", "Helvetica Neue", sans-serif',
};
EOF

echo "✅ Token map written to $TOKEN_FILE"
echo "🖖 Logical consistency of visual styling now supported across all components."
