#!/bin/bash

echo "🛠️ Chief O'Brien: Rebuilding LCARS Ultra Classic + Fonts + Layout system..."

# Set paths
STYLES_DIR="./styles/lcars"
OUTPUT_FILE="$STYLES_DIR/lcars24.css"

# Validate source files exist
REQUIRED_FILES=("lcars-ultra-classic.css" "lcars-fonts.css" "lcars-colors.css")
for file in "${REQUIRED_FILES[@]}"; do
  if [ ! -f "$STYLES_DIR/$file" ]; then
    echo "❌ Missing: $file in $STYLES_DIR"
    exit 1
  fi
done

# Merge all into lcars24.css with header
echo "/* LCARS 24 Unified Stylesheet */" > "$OUTPUT_FILE"
echo "/* Autogenerated by lcars24_merge_and_refactor.sh */" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for file in "${REQUIRED_FILES[@]}"; do
  echo "/* Begin: $file */" >> "$OUTPUT_FILE"
  cat "$STYLES_DIR/$file" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
done

echo "✅ LCARS 24 stylesheet created at $OUTPUT_FILE"
