#!/bin/bash
# 🛠️ Chief O'Brien: LCARS System Unification Script
# 🖖 Autogenerated on 2025-06-09 22:06:30
# This script merges LCARS stylesheets, ensures proper layout.tsx linkage, and cleans deprecated files.

set -e

echo "🛠️ Starting LCARS System Unification..."

# Directories
STYLE_DIR="styles/lcars"
PUBLIC_FONT_DIR="public/fonts"
LAYOUT_FILE="app/layout.tsx"

# Step 1: Create unified lcars-core.css
echo "🔧 Combining lcars-vars.css, lcars-colors.css, and lcars-ultra-classic.css..."
mkdir -p $STYLE_DIR
cat $STYLE_DIR/lcars-vars.css \
    $STYLE_DIR/lcars-colors.css \
    $STYLE_DIR/lcars-ultra-classic.css > $STYLE_DIR/lcars-core.css

echo "✅ Created $STYLE_DIR/lcars-core.css"

# Step 2: Update layout.tsx to reference lcars-core.css
if grep -q "lcars-core.css" "$LAYOUT_FILE"; then
  echo "ℹ️ layout.tsx already references lcars-core.css"
else
  echo "📝 Patching layout.tsx..."
  sed -i '' '/<head>/a\
    <link rel="stylesheet" href="/styles/lcars/lcars-core.css" />\
    <link rel="preload" href="/fonts/Antonio-Regular.woff2" as="font" type="font/woff2" crossorigin />\
    <link rel="preload" href="/fonts/Antonio-Bold.woff2" as="font" type="font/woff2" crossorigin />
  ' "$LAYOUT_FILE"
  echo "✅ layout.tsx updated"
fi

# Step 3: Clean deprecated stylesheet
DEPRECATED="$STYLE_DIR/lcars-fonts.css"
if [[ -f "$DEPRECATED" ]]; then
  echo "🧹 Removing deprecated $DEPRECATED"
  rm "$DEPRECATED"
fi

# Step 4: Summary
echo "🎉 LCARS System Patch Complete"
echo "📁 Unified Stylesheet: $STYLE_DIR/lcars-core.css"
echo "🔗 Layout File Patched: $LAYOUT_FILE"
