name: Production Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  production-test:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Make scripts executable
        run: |
          chmod +x amplify-prebuild.sh
          chmod +x scripts/production-test.sh
      
      - name: Run prebuild script
        run: ./amplify-prebuild.sh
      
      - name: Build application
        run: npm run build
      
      - name: Start server and run health check
        run: |
          npm run start & 
          SERVER_PID=$!
          
          # Wait for server to start
          echo "Waiting for server to start..."
          MAX_RETRIES=30
          RETRY_COUNT=0
          SERVER_READY=false
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            if nc -z localhost 3000 >/dev/null 2>&1; then
              SERVER_READY=true
              break
            fi
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo -n "."
            sleep 1
          done
          
          echo ""
          
          if [ "$SERVER_READY" = true ]; then
            echo "Server started successfully on http://localhost:3000"
            
            # Run health check
            echo "Running health check..."
            HEALTH_CHECK_RESULT=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
            
            if [ "$HEALTH_CHECK_RESULT" -eq 200 ]; then
              echo "Health check passed (HTTP 200)"
              kill $SERVER_PID
              exit 0
            else
              echo "Health check failed (HTTP ${HEALTH_CHECK_RESULT})"
              kill $SERVER_PID
              exit 1
            fi
          else
            echo "Server failed to start after ${MAX_RETRIES} seconds"
            exit 1
          fi
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next/
          retention-days: 7
